version: '3.8'

services:
  db-psql:
    image: postgres
    container_name: storage-psql
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_DB: storage_db
      POSTGRES_PORT: 5432
      POSTGRES_USER: supervisor
      POSTGRES_PASSWORD: qwer
      POSTGRES_SSL_MODE: disable
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "54321:5432"

  storage-service:
    container_name: storage-service
    build: .
    # extra_hosts:
    #   - "discovery:158.160.26.1"
    cpu_shares: 512
    mem_limit: 1g

    environment:
      STORAGE_FOLDER: "/storage"
      STORAGE_PORT: "80"
      DISCOVERY_ADDR: 158.160.26.1:80
      SERVICE_IP: 84.201.139.249
      POSTGRES_HOST: db-psql
      POSTGRES_DB: storage_db
      POSTGRES_PORT: 5432
      POSTGRES_USER: supervisor
      POSTGRES_PASSWORD: qwer
      POSTGRES_SSL_MODE: disable
      PORT_PING: 7010
      FILE_PORT: 7080
      FOLDER_PORT: 7000
      FOLDER_SERVICE_NAME: FolderGrpcService
      FILE_SERVICE_NAME: FileGrpcService
      GRPC_GO_LOG_VERBOSITY_LEVEL: '99'
      HTTP_PROXY: 158.160.26.1:80

      # GRPC_GO_LOG_SEVERITY_LEVEL: 'info'
      GRPC_TRACE: 'all'
      GRPC_VERBOSITY: 'DEBUG'

    ports:
      - "7010:7010"
      - "7000:7000"
      - "7080:7080" 
      - "80:80"

    volumes:
      - storage-voluem:/storage

    depends_on:
      - db-psql

volumes:
  storage-voluem: