CREATE TABLE folders (
	id BIGSERIAL NOT NULL PRIMARY KEY,
	user_id BIGINT NOT NULL,
	folder_name VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS files (
	id BIGSERIAL NOT NULL PRIMARY KEY,
	folder_id BIGINT NOT NULL,
	filename VARCHAR(100) NOT NULL,
	url text
);